export const COMMENT_FIND_BY_POST_ID_START = 'COMMENT_FIND_BY_POST_ID_START';
export const COMMENT_FIND_BY_POST_ID_OK = 'COMMENT_FIND_BY_POST_ID_OK';
export const COMMENT_FIND_BY_POST_ID_NOK = 'COMMENT_FIND_BY_POST_ID_NOK';