export const POST_FIND_ALL_START = 'POST_FIND_ALL_START';
export const POST_FIND_ALL_OK = 'POST_FIND_ALL_OK';
export const POST_FIND_ALL_NOK = 'POST_FIND_ALL_NOK';

export const POST_FIND_BY_NAME_START = 'POST_FIND_BY_NAME_START';
export const POST_FIND_BY_NAME_OK = 'POST_FIND_BY_NAME_OK';
export const POST_FIND_BY_NAME_NOK = 'POST_FIND_BY_NAME_NOK';